### ISSUE TITLE
Bug: can't find files in relative path when use in Windows OS

### ISSUE THREAD

**Issue by lucasfontesgaspareto** [tada5hi/typeorm-extension#463]
### Versions
- Node: 18.13.0
- OS: Windows 11

### Reproduction

<details open>
<summary>Additional Details</summary>
</details>

### Steps to reproduce
Use typeorm-extension in windows with relative path

### What is Expected?
Import seeds and factories

### What is actually happening?
typeorm-extension can not find files for seeds and factories

i managed to fixed it by change the path from windows like to unix like as you guys can see below

```
// eslint-disable-next-line @typescript-eslint/no-var-requires
const os = require('os')

let seedsPath = resolve(__dirname, '../../database/seeders/*{.ts,.js}')
let factoriesPath = resolve(__dirname, '../../database/factories/*{.ts,.js}')

if (os.platform() === 'win32') {
  seedsPath = seedsPath.replace(/\\/g, '/')
  factoriesPath = factoriesPath.replace(/\\/g, '/')
}
```

**Comment by tada5hi** [comment]
The problem is that glob matching is based on unix paths, so so far the paths have to be defined relative to the root directory with posix (`/`) path syntax. But I will soon enable the compatibility for windows paths as well :v:. Sorry for the inconvenience, but I'm glad you found a workaround right away :blush: .
